### ISSUE TITLE
Saved video is empty

### ISSUE THREAD

**Issue by 1j01** [positlabs/temporalis#9]
It saves a webm file of 0 bytes.

In the console:

```
SlitScan.js:5 SlitScan
index.js:98 record video undefined
Recorder.js:37 MediaRecorderaudio
  BitsPerSecond: 0
  ignoreMutedMedia: true
  mimeType: "video/webm; codecs=vp9"
  ...
index.js:98 record video undefined
index.js:134 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at HTMLInputElement.<anonymous> (index.js:134)
```

**Comment by positlabs** [comment]
Can you list steps to reproduce this issue?

**Comment by 1j01** [comment]
I tried starting recording after loading a video as well as before (in order to try to capture the whole thing.)
Then I clicked "record video" again to finish, either before the source video finishes or after.
I tried it in Chrome before; just tried it in Firefox and it doesn't work there either.

**Comment by positlabs** [comment]
Thanks for catching that! Seems like they changed how MediaRecorder works in Chrome 56. Try the latest and let me know if that works for you.

**Comment by 1j01** [comment]
It works, thanks!
